fix: path

diff --git a/.github/workflows/sonar-build.yaml b/.github/workflows/sonar-build.yaml
--- a/.github/workflows/sonar-build.yaml
+++ b/.github/workflows/sonar-build.yaml
@@ -33,7 +33,7 @@ jobs:
           # Display JAVA_HOME contents for debugging
           echo "JAVA_HOME is set to $JAVA_HOME"
           echo "Contents of $JAVA_HOME:"
-          ls -R "$JAVA_HOME"
+          ls -R "$JAVA_HOME" || { echo "JAVA_HOME not found"; exit 1; }
 
           # Locate the actual path of cacerts by checking broader directories
           CACERTS_PATH=$(find "$JAVA_HOME" /etc/ssl/certs/java /usr/lib/jvm -name "cacerts" 2>/dev/null | head -n 1)
